### PR TITLE
Update README.ru.md

### PR DESCRIPTION
**Pull request by vanja-san**
Sorry. Finished.

### CODE REVIEW

**Comment by binarynonsense** [comment]
I didn't notice those were missing ;)

**Comment by vanja-san** [comment]
@binarynonsense It's mostly about people and then what they did.

**Comment by binarynonsense** [comment]
The way I'm writing it in the readme is the other way around, about the things contributed and then who did it :) But don't worry, it's fine like that, I don't want to bother you more with such a small detail.

**Comment by vanja-san** [comment]
@binarynonsense No problem, if something looks as weird as possible, I'm willing to listen. 🫡

**Comment by binarynonsense** [comment]
:) I think we'll leave it as it is. I'll use the new readmes and the updated localization to make a new release, 2.4.1, when I have some time to build and test it. Thanks for contributing to the project!

**Pull request merged**
