### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Great, thanks for taking the time to find the right translation.

**Comment by vanja-san** [comment]
@binarynonsense Glad to try!

**Comment by vanja-san** [comment]
@binarynonsense Maybe I'll do a README-RU.md?

**Comment by binarynonsense** [comment]
Ok, sounds good. I'll create a docs folder in the project to put the translated readmes and then link them from the main one. Let me create the folder and the Spanish one so things are in place and I'll let you know when things are ready. I think the name should be README.ru.md (I'll create a README.es.md and a copy of the english one called README.en.md)

**Comment by binarynonsense** [comment]
Done, if you want to make the Russian readme I've created the structure for it.

**Pull request merged**
