### PR TITLE
Create README.ru.md

### PR DESCRIPTION
**Pull request by vanja-san**
Russian README

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks! I'll make a couple of tweaks after merging it to some of the links so they work fine and their text is right (the name of the languages at the beginning have to be each on their native language) but it looks great.

**Comment by binarynonsense** [comment]
I've made the tweaks and it's mostly done. Just a small doubt: you translated Contributions to Вклад, but google translate says that's a singular word, contribution... is google wrong or should we change it to the plural version of the word? (if that's the case let me know here what it should be and I'll change it, no need to make a pull request just for that)

**Comment by vanja-san** [comment]
@binarynonsense Well, you can even use "Участники вклада"

**Comment by vanja-san** [comment]
I think I forgot to translate something. 😮

**Comment by binarynonsense** [comment]
Isn't that more like contributors, not contributions? It's a small difference so we could use it. The idea is that it's a list of contributions, not just of contributors, although it includes them... anyway, it's a very small difference so any plural version, contributions or contributors is fine, I'll let you decide, which one do you think better reflects what I'm trying to convey?

**Comment by binarynonsense** [comment]
> I think I forgot to translate something. open_mouth

which part, I didn't notice :)

**Pull request merged**
