### PR TITLE
Update german

### PR DESCRIPTION
**Pull request by trzyglow**

### CODE REVIEW

**Comment by trzyglow** [comment]
sidenote: I think "Text direction" would be easier to understand than "Language direction"

**Comment by binarynonsense** [comment]
Thanks!!

**Comment by binarynonsense** [comment]
"Language direction" in this case is the direction the language is read, for example Arabic is right to left and English left to right.  I feel like "text direction" doesn't convey that in this context, at least in English or Spanish, maybe in German it does.

**Comment by binarynonsense** [comment]
If you are curious, this relates to me trying to add support for rtl languages after a contributor added Arabic localization. You can read about how it's going here: https://github.com/binarynonsense/comic-book-reader/pull/110

**Comment by trzyglow** [comment]
"Text Orientation" might be the correct tern (at least it is in regards to 'up to down' text like in some east asian languages)

**Comment by binarynonsense** [comment]
Maybe I didn't explain it too well, what I mean is this text will be an option in the preferences for toolbar, named direction, where you will choose between "Language Direction", "Right to Left" and "Left to Right". With Language Direction implying that instead of chossing one you let the app use the direction from the current language... maybe it'd be better to name it "Use Language Direction", or "Same as Language Direction"? I feel like text orientation doesn't convey it either.

**Comment by trzyglow** [comment]
"Writing System" is probably the most accurate since it implies both alphabetical differences and differences in formatting

**Comment by binarynonsense** [comment]
In UI design and css they use the term direction (and it limits itself only to left to right or right to left), and I would like to make clear that with this option the value is inferred from the chosen Language.

**Comment by binarynonsense** [comment]
This is specific to the horizontal direction in which the UI, in this case the toolbar, is set. For ltr "mode" it's like it has been so far, but in "rtl" most things are mirrored. what I'm trying to convey is that the horizontal layout is set to ltr or rtl either by setting it explicitly or inferring it from the selected language, which can of ltr (English) or rtl (Arabic) direction. 
This is all a bit new to me, so I'm figuring things out as I go :)

**Comment by binarynonsense** [comment]
Maybe "Infer from Selected Language"?

**Comment by trzyglow** [comment]
i think so, too;
most other things i could find are even more vague

**Comment by binarynonsense** [comment]
Yeah, I have a lot of trouble some times trying to find something sort but meaningful :) I'll change it to "Infer from Selected Language" then. Thanks for the feedback!!

**Pull request merged**
