### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by trzyglow**
- adds a translation for the new "outdated" tag
(since it was added after my previous pr, and idk if a sync can mess up a master to master pr)

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!

**Comment by binarynonsense** [comment]
In the case of "Cache Downloads", cache would be a verb (a shorter way to say store the downloads in the cache)

**Comment by trzyglow** [comment]
I'll quickly fix that, there is no german word for cache (at least for this context) and download (only for the act of downloading).

**Comment by binarynonsense** [comment]
I f you think it's best to leave it in English that's ok.

**Comment by trzyglow** [comment]
i just fixed the folder line on my end, so it'll be in the next pr

**Comment by binarynonsense** [comment]
Perfect, thanks!

**Pull request merged**
