### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by vanja-san**
fully

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks a lot!!!

If you someday have the time, the Russian readme
https://github.com/binarynonsense/comic-book-reader/blob/master/docs/README.ru.md
is a  bit out of date compared to the English one
https://github.com/binarynonsense/comic-book-reader/blob/master/docs/README.en.md

**Comment by binarynonsense** [comment]
is  "ui-modal-prompt-button-edit-metadata": "Изменить методанные", a typo?
should it be  "ui-modal-prompt-button-edit-metadata": "Изменить метaданные", ?
I'm just noticing it because it's the only place where you wrote metadata like that, I don't speak Russian so it may be that that's the way in that case for some reason, but just wanted to make sure :)

**Comment by vanja-san** [comment]
@binarynonsense You are right, I made a grammatical error.

**Comment by binarynonsense** [comment]
No problem, seemed like a typo but wanted to ask just in case.

**Pull request merged**
