### PR TITLE
Update README.de.md

### PR DESCRIPTION
**Pull request by trzyglow**
- fixed capitalization for a line
- removed a few periods

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!

What's the reasoning for deleting the periods in some lines and not others? I think of each branch as a sentence, so I end them with one, but you now end some and not others and I'm not sure I see the pattern.

**Comment by trzyglow** [comment]
> What's the reasoning for deleting the periods in some lines and not others?

mainly visual distinction between the more list-like entries and the more sentence-like ones.

**Comment by binarynonsense** [comment]
I never looked into this so I'm reading a bit and there doesn't seem to be a set of rules everyone agrees on, in English (haven't looked at the issue in Spanish).

I think I'm gonna tweak slightly the English ones to follow my interpretation of these (start the subranches that are part of a bigger sentence with lower case and remove the periods from the few ones that aren't sentences and just a brief list of formats for example):

https://www.microsoft.com/en-us/microsoft-365-life-hacks/writing/punctuating-bullet-point-lists
https://www.theukrules.co.uk/rules/lifestyle/writing/bullet-points/

I'll let you decide on the German one, as these clearly varies from language to language and sometimes is more of a preference.

**Comment by binarynonsense** [comment]
Nah, I'm going to leave them ending with a period, for consistency. I started to edit it and if I follow these some lines in the same list would need them others not... I may change my mind but right now I don't like how that looks :)

**Comment by trzyglow** [comment]
Funnily enough, I've found a page on different rulesets regarding bulletpoints in german; but not even governmental institutions seem to follow it.

**Comment by binarynonsense** [comment]
The official ones I've found for Spanish are similar to the ones I chose for English, from a very quick read, but there are even some times when you can choose to use a semicolon... The English ones are all over the place, doesn't seem to be a consensus.

I tried to edit the English readme again and still feels weird to me to follow those rules, as there are always unclear cases and then everything ends up feeling inconsistent.

**Comment by trzyglow** [comment]
Yeah, I'm gonna add back the periods, probably better consistency-wise in the long term.

**Comment by binarynonsense** [comment]
I'm a bit torn about it for the English and Spanish ones, between correctness and visual consistency. I think something like this would be more correct and maybe doesn't look bad? (Everything that is clearly a list item ends with no period, Sentences that are long enough end with period... but there are some that could be seen either way...)

- Windows & Linux versions
- Compatible file formats:

  - Comic books:
    - CBZ, CBR, CB7, PDF and EPUB<sup>[1]</sup>
  - Image files:
    - JPG, PNG, WebP and AVIF
  - Ebooks:
    - PDF and EPUB<sup>[2]</sup>

  Including password protected PDF, CBZ (AES encryption not supported), CB7 and CBR files.

- Windowed (simple UI) and full-screen (no UI) modes
- 'Fit to width', 'fit to height' and a customizable 'scale to height' page views
- Page rotation
- UI available in:
  - English, Spanish, Russian, German and Arabic
- Automatically restores the previous session's last opened book and page, and remembers the last books' page positions.
- Portable mode (by creating a file named portable.txt in the same folder as the executable)
- ComicInfo.xml editor:
  - View the metadata stored in ComicInfo.xml files inside CBR, CBZ and CB7 comic books.
  - Create and/or modify the metadata stored in ComicInfo.xml files inside unencrypted CBR<sup>[3]</sup>, CBZ and CB7 comic books.
  - Search for and import comic book metadata from Comic Vine (a [Comic Vine API key](https://comicvine.gamespot.com/api/) is required).
- Integrated audio player:
  - Supports MP3, Ogg, WAV, M3U and M3U8 files.
  - Can export playlists to M3U files.
- Tools:
  - Convert/Resize:
    - Comic books (CBR, CBZ, CB7, PDF or EPUB<sup>[1]</sup> to CBR<sup>[3]</sup>, CBZ, CB7, PDF or EPUB)
    - Images (JPG, PNG, AVIF or WebP)
  - Create:
    - A comic book (CBR<sup>[3]</sup>, CBZ, CB7, PDF or EPUB) from a list of image files and/or comic books
    - A QR code image from text
  - Extract:
    - Comic book pages (to JPG, PNG, AVIF or WebP)
    - Text (OCR) from a comic book page or image file
    - A QR code's text from a comic book page or image file
    - A color palette from a comic book page or image file
      - Can be exported to a GPL or ACO palette file.
  - Other:
    - Search and open books/comics from:
      - Digital Comics Museum
      - Internet Archive Books
      - Project Gutenberg
      - xkcd Webcomics
    - Search and open audiobooks from:
      - Librivox AudioBooks
    - Search dictionary terms from:
      - Wiktionary Dictionary
    - Search and open radio station streams from:
      - radio-browser

**Comment by binarynonsense** [comment]
I'm going to go this route for now and se how it feels, but let me know what you think.

**Comment by trzyglow** [comment]
looks good to me, I'll go the same route for the german doc

**Comment by binarynonsense** [comment]
Great!.

**Pull request merged**
