### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by trzyglow**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!

**Comment by binarynonsense** [comment]
The Russian localization file and documentation is getting quite out of date, so I'll mention @vanja-san here hoping they'll get a message (I have no other means of contact) and have the time to update them some day.

**Comment by vanja-san** [comment]
@binarynonsense ok, i soon complete

**Comment by binarynonsense** [comment]
@vanja-san Thanks! No rush, take all the time you need.

**Pull request merged**
