### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by ahmed-0011**
Some entries are kind of unclear. For example, the new four entries for tool-shared-tooltip-move-*
I think there are only vertical lists (for example, input file lists) in ACBR, so the context for the new entries is not clear.

Also, for the six changePage* entires, I wasn't sure if I should remove the parenthesis and its content, but in the end, I did remove them anyway.

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks for the update!

- The tool-shared-tooltip-move-* entries are for current lists but also to be prepared for potentially future ones. Next and previous are another way to move through a list, not by their visual position like the others but their position linearly on the underlying list. It's just to have a backup way to move for some cases where the UI may change its arrangement (number of columns/rows) on the fly so I can just have those to move without a spatial reference (don't know if I'll have to use them).
Anyway, I've added this note to the files to hopefully make it more clear:

` "[NOTE TO TRANSLATORS]tool-shared-tooltip-move-next-in-list": "'Move Next' can also be translated to the localized version of 'Move to Next', 'Move to the Next' or 'Move to the Next Position', whichever makes more sense in the target language. Same for 'Move Previous'",`

Feel free to change the localization if you think you have now a better way to translate those.

- Anything inside the quotes is part of the text to be translated, notes go on their own lines withe the [NOTES TO TRANSLATORS] tag. In this case (Change Page) has to be also tranlated, and it's there to give more context to the action name (this is used in the key mapping in the preferences).
I've re-added it to those lines and marked them again as [NEEDS TRANSLATION], please update them if you have the time.

**Comment by ahmed-0011** [comment]
Thank you for clarifying.

If you implemented 2D lists at some point, don't you think it's better to support drag and drop to re-order the items instead of having many buttons? (I'm not sure if this technique is good for accessibility).

I made a new pull request with the required changes and I checked to see if the other localizations have the parenthesis content translated, and I find that mostly they did, but in some of the german translation entries the parenthesis are omitted, this is just fyi.

**Comment by binarynonsense** [comment]
Yes, that's the plan, I'd like to add drag and drop to 2d lists (maybe some day to the already existing 1D ones), but also need to have buttons or menus to do it in some situations as a fallback/alternative option (for people who prefer that / accessibility or maybe or use gamepad)...

In fact, I added them with one list in mind, the favorites in the home screen. I want to make it drag and drop sortable some day, probably not at first though, and also add to the options menus they have the move forward and backward buttons (this will be what I'll add first as it's the easiest and works for everyone).

I'll check the German translation later to let Timo know if some of those (change page) parenthesis is missing, thanks.

**Comment by binarynonsense** [comment]
Yes, I checked and Timo in the pull request for those lines told me: "Tweaked the text a bit to make it gramatically more coherent in german".

The German translation of the ones without the (change page) already include the concept of changing page in the text itself, so there's no need to clarify it refers to changing pages, and if translating the English version too literally sounds off I have no problem with the translator going for a better alternative as long as the same idea is conveyed.
Back to English the German lines say:
> "changePageRight": "Go right (change page)",
> "changePageLeft": "Go left (change page)",
> "changePageNext": "Go to next page",
> "changePagePrev": "Go to previous page",
> "changePageFirst": "Go to first page",
> "changePageLast": "Go to last page",`

Same as with Timo, you can choose which way to go, if you feel like translating it close to the English way can't be done without sounding weird and think that a translation similar to the German one sounds better feel free to do it.

**Comment by ahmed-0011** [comment]
Ok, I probably will do the same thing, only the first two entries include the parenthesis.

**Pull request merged**
