### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by ahmed-0011**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!

**Comment by binarynonsense** [comment]
I'm going to change the English translations to Move Forward and Move Backward, which I think is what you went for in Arabic, as it sounds better.

**Comment by ahmed-0011** [comment]
You are absolutely right. Yes, I think they are more accurate.

**Comment by binarynonsense** [comment]
Now it feels obvious to me but if it wasn't for you I would still be fixated with the next/previous idea :)

**Pull request merged**
