### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by al-dev112233**
Changed a few typos and made enhancements to make the expressions more smooth.

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks for the pull request, @trzyglow started and has been regularly maintaining the german translation, so I'd need their input before accepting any of these changes.

**Comment by binarynonsense** [comment]
I don't speak german, so hopefully @trzyglow will be able to add more to the discussion but from a quick look it seems like you changed the capitalization of some of the words that are not the starting letter of the phrase (but not others?). Is that strictly needed? did you take a look at the english, reference, localization file and/or how the text looks in the menus in the program itself to check how things currently look? In the english localization some words are capitalized for aesthetic reasons (I just feel they look better that way in the menus) and the current german translation respects that so, unless its too ugly/strange for a german reader I'd like to keep all the translations adhering to that.

**Comment by binarynonsense** [comment]
For the menus' text capitalization, one of my visual references is the firefox toolbar, so taking a look at what they do in the german localization could be a good starting point.

Screenshot_20230730_201046_zoom

Screenshot_20230730_201101_zoom

**Comment by trzyglow** [comment]
It's mostly valid:

- most changes, just revert the stylistic adaptations i kept from the english original.
- although i deliberately chose to use "konvertieren" instead of "umwandeln" because it's more accurately to the context.
- hanging "dem selben" with "demselben" is gramatically wrong in this context (atleast in standardized high german)
- there are also deletions to some segmentations i did for the sake of readability
- some new sentence translations omit information present in all other translations

also: yes, i do get notified when mentioned.

**Comment by binarynonsense** [comment]
I think this commit is too big and changes too many things at one time, sometimes getting away too much from the original english localization's content or some of the style. Correct me if I'm wrong, as I said I don't speak german and rely only on google translate, but I also noticed things like the translation for the File>Quit text that are more verbose that I feel they should be (quit program instead of quit) or the description of some of the tools suggesting donating to the websites it makes use to referring to the program instead of the tool, losing a bit of the original meaning... feels like some texts have been modified taking into account only the previous german translation and not the original english or the context within the program...

@al-dev112233 maybe it would be best if you closed this pull request and  discussed some of the changes you feel are more important here with @trzyglow and me, and once there are a few we all feel improve things you can make a new, smaller pull request with them, and so on. Don't know how you all feel about this approach.

By the way, I'm working on a big rewrite of the program internals and UI (which will become version 3.0) and I've made some changes to the localization files, so maybe it would be best if you waited until I update the repository to make pull requests, as I've already made some name changes and have added new entries that need translations and merging changes now will make things a bit messy on my end before that (I don't know when I'll be ready to make the current changes public, things are quite broken right now, but I'm getting slowly there).

**Comment by al-dev112233** [comment]
I see, I'll wait for the new version.

**Pull request closed without merging**
