### PR TITLE
Update README.de.md

### PR DESCRIPTION
**Pull request by trzyglow**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks! I guess you saw it in the Russian localization and went ahead and added it. As I said to vanja-san I'll delete it for now, but will keep it to add it when the next update is available (as seeing the mention to Arabic in the public documentation could make some users think it's available in the version they can download right now). I asked them to add it because some times I have trouble contacting them and this way I'm already ready for when it's needed.

**Comment by binarynonsense** [comment]
Now I'm not sure what to do... :) I may leave it already there and add it to the Spanish and English ones. I didn't want people to get confused, but as long as I don't put Arabic in the Features list I think it'd be ok, and they already made the contribution so it seems fair to already acknowledge it, what do you think?

**Comment by trzyglow** [comment]
I'd be fair to acknowledge it, allthough for the meantime it'll be wise to also add some sort of "To be implemented" disclaimer to mitigate confusion.

**Comment by binarynonsense** [comment]
I agree, we'll do that. I'll leave the Russian one as it is, because I don't want to ask vanja-san to make another change so soon given it's just a small detail, but I'll do it for the English and Spanish ones and if you don't mind, do the same for the German one.

**Pull request merged**
