### PR TITLE
update german localization

### PR DESCRIPTION
**Pull request by trzyglow**
translated the new entries.

**_in a couple of entries i wasn't quite sure if "line" refers to "line" as in "a line of text" or "line" as in "a drawn line", because in german those are 2 different words; so those specific new translated entries may be inaccurate._**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!

Line is used in the drawing sense in most places, only in "line spacing" in the header line spacing refers to text lines.

Until I release a version containing it, to see the terms in context you can check an online version of the tool the one in ACBR is a port of here: http://www.binarynonsense.com/webapps/template-maker/

Also, the words tree and node are used in this context: https://en.wikipedia.org/wiki/Tree_(abstract_data_type) (I'm not sure Gitterpunkte, for example, is taking this into account)

I'll add some more notes to translators to try to clarify some of this things.

**Comment by binarynonsense** [comment]
A minor nitpick: please try to start your commit messages with a capital letter and use always descriptive, short, sentences. Just noticed in one of your latest commits it is just a dot:
https://github.com/binarynonsense/comic-book-reader/commits/master/

**Comment by trzyglow** [comment]
> Also, the words tree and node are used in this context: https://en.wikipedia.org/wiki/Tree_(abstract_data_type) (I'm not sure Gitterpunkte, for example, is taking this into account)

Gitterpunkt means of "node of a grid", otherwise "Knotenpunkt" just means node (in a very general way)

**Comment by binarynonsense** [comment]
In this case the nodes are part of a tree, not a grid, and the tree is a representation of a grid... so the concept of node is not grid-specific but tree-specific, if that makes sense. A longer version of what I'm trying to represent would be something grid tree-view nodes or something like that (sometimes I may go too far trying to reduce things to the smallest version so the UI fits better :) although I think, in English, this one works; in Spanish I translated it to 'nodos de cuadrícula (vista de árbol)' which sounds a bit strange but I think works too if you know what the subtool to create grids does).

If you still think that's the translation that conveys that that's it but just in case it makes any difference when localizing it.

**Comment by trzyglow** [comment]
> In this case the nodes are part of a tree, not a grid, and the tree is a representation of a grid... so the concept of node is not grid-specific but tree-specific, if that makes sense. A longer version of what I'm trying to represent would be 'grid tree-view nodes' or something like that (sometimes I may go too far trying to reduce things to the smallest version so the UI fits better :) although I think, in English, this one works; in Spanish I translated it to 'nodos de cuadrícula (vista de árbol)' which sounds a bit strange but I think works too if you know what the subtool to create grids does).
> 
> If you still think that's the translation that conveys that that's it but just in case it makes any difference when localizing it.

Nodos de cuadrícula literally translates to "Gitterpunkte" in german.

**Comment by binarynonsense** [comment]
This is making me think I should rename this one to just "grid (tree view)", similar as to how the one for the header is just "header text (tree view)". I'm going to do that (I'll delete the German one too so you know it's been changed and can re-localize it).

**Pull request merged**
