### PR TITLE
Add READEME.ar.md and translate some entries in ar.json

### PR DESCRIPTION
**Pull request by ahmed-0011**
This pull request adds READEM.ar.md, which is the Arabic documentation for ACBR, and it also includes the translations for the new entries in ar.json.

It's almost complete, but there are some issues with the direction of some of the bullet points.
I couldn't find the exact part of the text that causes the issue yet, and I tried to use <div dir="rtl" align="right"> for the text, but it's not working.

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!

Yes, seems like some bullet points align to the left and others to the right in the features section, but the others look right :S I don't know if I can be of much help as just trying to edit it to make some tests makes me get a bit lost when it suddenly changes sides depending on the language direction of some lines... :)

I'll link it anyway from the other docs, but it'd be nice if we could figure out the problem with the markdown to make it look nicer.

**Comment by binarynonsense** [comment]
Another thing that needs fixing is the Contents section shortcuts, you probably need to use the Arabic text from the headers after the # in the links instead of the English one.

**Comment by binarynonsense** [comment]
I think I managed to make it look better.

**Comment by ahmed-0011** [comment]
Looks great!

So, the issue was mainly because of some bullet points that start with English letters?

For the shortcuts, I was not sure if I should change them, but right now they are useless and not functional, so I'm going to update the file soon and change the hash fragments to Arabic.

**Comment by binarynonsense** [comment]
That's probably it but, to be honest, I'm still not 100% sure, in the end I got annoyed with it and just used trial and error until I figured out that mixing those ones in one line instead of having another indentation level, which still makes sense and looks fine, fixed it :)

Yes, if you don't translate those hashes too the links don't work. I seem to remember there where issues when there were spaces in the header name the hash points to, I don't remember exactly (and currently there aren't any headers in any of the other languages where that's the case) if that didn't work and you had to add a hyphen to the hashtag or just delete the spaces or something... I may be misremembering, but just in case you encounter that problem.

**Comment by binarynonsense** [comment]
I fixed the Contents section links, looking at the code generated by github I just had to copy and paste the anchor names so it was quick.

**Comment by ahmed-0011** [comment]
Yeah, this is exactly what I did before noticing that you made a new pull request with the changes.

So, I just went ahead and updated some parts of the file in my last pull request :)

**Comment by binarynonsense** [comment]
Great, I think everything works and looks good now.

**Comment by ahmed-0011** [comment]
Thanks for the clarification, because initially I thought it was an exe installer.

I think that 'Self-Extracting' can't be translated directly to Arabic, so I had to include more information about what this executable file does.

PR: #146

**Pull request merged**
