### PR TITLE
update ru

### PR DESCRIPTION
**Pull request by vanja-san**

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!

**Comment by binarynonsense** [comment]
By the way, I noticed you've updated your name in your profile, do you want me to update your name in the contributions to

Russian localization by Ioan (vanja-san)? like with other contributors.

Let me know if you want me to do that (no need to do anything if you are happy with/prefer just vanja-san, but just in case you'd like to update it I thought I should mention it, it's no problem at all. And you can update it in the Russian localization file' authors if you want, so it is used in the localization.txt credits file).

**Comment by vanja-san** [comment]
@binarynonsense Let everything be as it is! 😁

**Comment by binarynonsense** [comment]
OK, no changes needed then :)

**Pull request merged**
