### PR TITLE
Update German Localization

### PR DESCRIPTION
**Pull request by trzyglow**
- translated the new stuff
- fixed some of my old stuff i stubmbled across on my own (minor optimization)
- took a few parts of al-dev112233's PR that made sense to keep (and properly implemented them to retain consistency)
- renamed "UI" to the german "Benutzeroberfläche" in the doc, since it's now in the localization file

note: 
some changes in al-dev112233's PR were irrelevant since they're just alternative spellings of the same words, and mostly just dialect based (in regards to which get's used more commonly); others were "too german" to the point were some elements started to lose their initial meaning in the context of the program. (also a few lines were misinterpreted to be mistakes, even though they weren't)

### CODE REVIEW

**Comment by trzyglow** [comment]
on the general topic of localizations:
it would make sense to add "[УСТАРЕВШИЙ]" next to the tag for the russian language option, since it hasn't been updated for a couple of versions. (it's just deprecated/outdated in russian)

**Comment by binarynonsense** [comment]
Thanks!

As for the russian localization, I agree, I was thinking of doing that for the future release of version 3 if it hasn't been updated by then (I still have work to do to finish it, as I have to rewrite most of the tools to use the new UI and  code structure). 
Some time ago I added the "tool-pre-languages-incompletelanguages" entry in the localization files a way to automate adding it to the name of the language based on the file version to do just that, so it would be easy. The only problem is with the way the new UI shows things now I'd need the new "tool-pre-languages-incompletelanguage", the singular word, to be translated in the russian localization, so I can write it like: Language-natural-name (Incomplete), with Incomplete being the translation for the current language of the UI. 
Do you know what would be the correct translation in russian would be for "Incomplete" (right now it only has the translation for the plural).
Maybe "Outdated" (but not all in caps, I'd have to test how that would look and I prefer to do that in code anyway so I have more flexibility with how I can use the words, and be able to use it different ways) is a better term... what do you think?, in that case I'd need to add it to all translation files, including the russian one too.

**Comment by trzyglow** [comment]
I only know some basic russian (the slavic language i have the least experience with, especially when it comes to written grammar), as for "incomplete" I guess "непо́лный" would be closer, but it definitely should be looked over by a native speaker.

**Comment by binarynonsense** [comment]
What about "Outdated", if you are surer about the translation for that we could go use it. In any case, I'll mention @vanja-san here, the creator of the original Russian translation, in case they read this and have time to update the file, or at least tell us the correct translation for "Incomplete" and "Outdated".

**Comment by binarynonsense** [comment]
I just noticed you translated "Color Themes" but not "Color Theme", was that on purpose?

**Comment by trzyglow** [comment]
nope, i just overlooked that during the translation, it'll be fixed in the next pr

**Comment by binarynonsense** [comment]
Great, no rush, just wanted to make sure.

**Comment by vanja-san** [comment]
@binarynonsense Done!

**Comment by binarynonsense** [comment]
Thanks a lot @vanja-san !!

**Pull request merged**
