### PR TITLE
completed

### PR DESCRIPTION
**Pull request by vanja-san**
ru

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!!!

- Next time, don't delete the [NOTE TO TRANSLATORS] lines, as I like to keep them on all files so the number of lines are the same and for future reference for the translators.
- If you have the time, could you update the documentation file? https://github.com/binarynonsense/comic-book-reader/blob/master/docs/README.ru.md It's really out of date compared to the others.

**Comment by vanja-san** [comment]
@binarynonsense

Sorry, I thought they should be deleted, but I won’t do it again.  I'll get to it soon.

**Comment by binarynonsense** [comment]
> @binarynonsense
> 
> Sorry, I thought they should be deleted, but I won’t do it again. I'll get to it soon.

@vanja-san don't worry about it, just wanted to let you know for future updates, but it took no time to paste them back.

The localization files have some new entries again (I'm working on adding some new features for the next update) so if you can, please update yours too. Thanks!!

**Comment by binarynonsense** [comment]
By the way @vanja-san, when you have time to translate the readme, could you add (translated) the line
Arabic localization by [Ahmed (ahmed-0011)](https://github.com/ahmed-0011)
to the contributions section
I'll probably delete it temporarily (as the current version doesn't include Arabic) but will store it so I can re-add it later because I'll need to include it to all the readmes when the next update is released, as that one will include a newly contributed Arabic localization, and this way I won't have to bother you again to add it (you can also not put it yet in the file itself but paste it in a comment so I can add it when it comes the time).

**Comment by vanja-san** [comment]
@binarynonsense done!

**Comment by binarynonsense** [comment]
Thanks a lot for this, I really appreciate it.

**Pull request merged**
