### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by vanja-san**
Full translated

### CODE REVIEW

**Comment by binarynonsense** [comment]
Thanks!

**Comment by binarynonsense** [comment]
I just noticed that the about tab in some tools  "tool-shared-tab-about" is translated to "О...". Is that right or a typo?

**Comment by vanja-san** [comment]
> I just noticed that the about tab in some tools  "tool-shared-tab-about" is translated to "О...". Is that right or a typo? Edit: never mind, I found it odd at first but google translate says about is translated to О and I guess it's a common thing to (or you chose to) add the dots to make it more clear what it means in this context (or longer to make the tab big enough, which is a good thing too).

I just didn't understand what it was about, that is "About ... name" and therefore left only "O..."

**Comment by vanja-san** [comment]
i.e. "About ABCR", "About comics"

**Comment by binarynonsense** [comment]
Each tool has a tab for the "about" section, which is where there's a text explaining what it is/does:

image

And the text for that tab is in that entry named "tool-shared-tab-about". I don't know what is traditionally used for a case like that in Russian, if it's usually just "O" let's use that (I'd prefer not to use the three dots, as in the menus I use the convention of three dots meaning another window will open, like in File>Open...), although it's a bit short and will probable make the clickable area a bit small (but I probably could adjust that in code to a minimum if needed).

**Comment by vanja-san** [comment]
@binarynonsense If it's okay, I could use "About Service" or in Russian, "О сервисе".
I'm trying to replace word "website" if it's even worth replacing. i.e. "About Website"

**Comment by binarynonsense** [comment]
@vanja-san In this case the long version would be "About the tool" or "About this tool", so if just "about" is too short/not descriptive enough, I would choose translating that instead if it's not too long.

**Comment by vanja-san** [comment]
@binarynonsense I'll just leave it at "site"

**Comment by binarynonsense** [comment]
Sorry, but that's not correct, the about information is about the tool, not a site, so the longer version would have to be something like "About this tool"

**Comment by vanja-san** [comment]
@binarynonsense ok 🤣

**Comment by binarynonsense** [comment]
:)

**Pull request merged**
